image: Visual Studio 2019
version: 1.8.3.{build}
platform: Any CPU
configuration: Release

before_build:
  - msbuild -t:restore "src\ParallelHelper.sln"

build:
  project: src\ParallelHelper.sln

before_test:
  - nuget install OpenCover -OutputDirectory packages -Version 4.7.922

test_script:
  - OpenCover.Console.exe -register:user -target:"vstest.console" -targetargs:"/logger:Appveyor /output:".\coverage.xml" src\ParallelHelper.Test\bin\Release\netcoreapp2.0\ParallelHelper.Test.dll"

artifacts:
  - path: src\**\*.nupkg
  - path: src\**\*.vsix
