image: Visual Studio 2019
version: 1.8.3.{build}
platform: Any CPU
configuration: Release

before_build:
  - msbuild -t:restore "src\ParallelHelper.sln"

build:
  project: src\ParallelHelper.sln

before_test:
  - nuget install OpenCover -OutputDirectory packages -Version 4.7.922

test_script:
  - packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -output:".\coverage.xml" -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"/logger:Appveyor src\ParallelHelper.Test\bin\Release\netcoreapp2.0\ParallelHelper.Test.dll"

artifacts:
  - path: src\**\*.nupkg
  - path: src\**\*.vsix
