image: Visual Studio 2019
platform: Any CPU
configuration: Release

build:
  project: src\ParallelHelper.sln

before_build:
  - msbuild -t:restore

artifacts:
  - path: src\**\*.nupkg
  - path: src\**\*.vsix
