image: Visual Studio 2019
version: 2.3.0.{build}
configuration: Release

before_build:
  - msbuild -t:restore "src\ParallelHelper.sln"

build:
  project: src\ParallelHelper.sln

before_test:
  - dotnet tool install --global coverlet.console --version 1.7.0

test_script:
  - ps: coverlet src\ParallelHelper.Test\bin\Release\netcoreapp3.0\ParallelHelper.Test.dll --target "dotnet" --targetargs 'test src\ParallelHelper.Test -c Release -logger:""C:\Program Files\AppVeyor\BuildAgent\dotnetcore\Appveyor.MSBuildLogger.dll"" --no-build' --format opencover --output coverage.xml

after_test:
  - ps: |
      if(-not (Test-Path env:APPVEYOR_PULL_REQUEST_TITLE)) {
        dotnet tool install --global Codecov.Tool
        codecov -f "coverage.xml"
      }

for:
-
  branches:
    only:
      - master
  artifacts:
    - path: src\**\*.nupkg
    - path: src\**\*.vsix
